spring.profiles.active=local

spring.application.name=bank

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_db
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT
jwt.expiration=36000000

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.bank.dto

# Hibernate SQL
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE