spring.profiles.active=local

spring.application.name=bank

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_db
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT
jwt.expiration=3600000