DROP TABLE notification;

CREATE TABLE notification(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    reference_type VARCHAR(20) NOT NULL,
    reference_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    message VARCHAR(255),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_notification_member_id
        FOREIGN KEY (member_id)
            REFERENCES member(id),

    CONSTRAINT fk_notification_reference_type
        CHECK ( reference_type IN ('TRANSACTION', 'AUTO_TRANSFER') )
);