
CREATE TABLE member(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(30) NOT NULL,
    phone VARCHAR(11) NOT NULL,
    email VARCHAR(100) UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_member_phone
        CHECK(char_length(phone) = 11)
);

CREATE TABLE account(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    account_number VARCHAR(12) NOT NULL UNIQUE, -- ex) 100123456789
    balance BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_account_member
        FOREIGN KEY (member_id)
            REFERENCES member(id),

        CONSTRAINT chk_account_account_number
            CHECK(char_length(account_number) = 12),

        CONSTRAINT chk_account_balance
            CHECK(balance >= 0),

        CONSTRAINT chk_account_status
            CHECK(status IN ('ACTIVE', 'FROZEN', 'CLOSED'))
);

CREATE TABLE transaction_history(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT,
    type VARCHAR(20) NOT NULL,
    amount BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    opponent_account VARCHAR(12),
    description VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_transaction_history_account_id
        FOREIGN KEY (account_id)
            REFERENCES account(id),

        CONSTRAINT chk_transaction_history_type
            CHECK (type IN ('DEPOSIT', 'WITHDRAW', 'TRANSFER_IN', 'TRANSFER_OUT')),

        CONSTRAINT chk_transaction_history_amount
            CHECK (amount > 0),

        CONSTRAINT chk_transaction_history_balance_after
            CHECK (balance_after >= 0),

        CONSTRAINT chk_transaction_history_opponent_account
            CHECK(
                opponent_account IS NULL
                    OR char_length(opponent_account) = 12
                )
);

CREATE TABLE notification(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    transaction_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    message VARCHAR(255) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_notification_member_id
        FOREIGN KEY (member_id)
            REFERENCES member(id),

    CONSTRAINT fk_notification_transaction_id
        FOREIGN KEY (transaction_id)
            REFERENCES transaction_history(id)
);

CREATE TABLE audit_log(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR(30) NOT NULL,
    target_id BIGINT NOT NULL,
    action VARCHAR(10) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_audit_log_table_name
        CHECK(table_name IN ('MEMBER', 'ACCOUNT', 'TRANSACTION_HISTORY', 'NOTIFICATION')),

    CONSTRAINT chk_audit_log_action
        CHECK(action IN ('INSERT', 'UPDATE', 'DELETE'))
);

